### ISSUE TITLE
Custom model does not get backfilled after removing from manifest

### ISSUE THREAD

**Issue by tuannguyenq4** [snowplow/dbt-snowplow-web#112]
### Describe the bug
According to #### Tearing down a subset of models section in https://snowplow.github.io/dbt-snowplow-web/#!/overview/snowplow_web, we want to tear down and full-reload a custom module. The module taking snowplow _this_run model as source.  We expect it would backfill from our custom start-date, but it does not.

It is blocked by is_run_with_new_events macro (since _this_run table is up-to-date, it will not replay events)

### Steps to reproduce
dbt run --select +snowplow_web_custom_incremental_model --vars '{snowplow__start_date: your_backfill_start_date, models_to_remove: snowplow_web_custom_incremental_model}'

### Expected results
snowplow_web_custom_incremental_model  get backfilled 

### Actual results
snowplow_web_custom_incremental_model  is empty 

### System information
packages:
  - git: "https://github.com/calogica/dbt-expectations.git"
    revision: 0.5.6
  - package: snowplow/snowplow_web
    version: 0.9.0
  - package: mjirv/dbt_datamocktool
    version: ">=0.1.10"

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [x] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.2.0
  - latest:    1.2.0 - Up to date!

Plugins:
  - snowflake: 1.2.0 - Up to date!
```

**The operating system you're using:**
Window 11
**The output of `python --version`:**
Python 3.9.13

**Comment by rlh1994** [comment]
Hi @tuannguyenq4 , sorry it's taken so long to look at this.

I've tried to reproduce this issue but have been unable to in a similar config (although I am using the 0.9.2 version of the web package). I've listed my steps below, can you please let me know if following these you still get the same issue?


Setup:
1. Have a dbt project with snowplow-web dependency
2. Create a custom model that `ref`s from a `_this_run` table, giving it a tag of `snowplow_web_incremental` in your project file, with this model using the `  where  {{ snowplow_utils.is_run_with_new_events("snowplow_web") }} ` condition.
3. dbt run a few times to populate both the main derived tables and your custom model, your model should appear in the manifest table and be in-sync

Prep for change of model:
1. Delete the custom model table from your snowflake database

Backfill model:
1. Run the `dbt run --select +snowplow_web_custom_incremental_model --vars '{snowplow__start_date: your_backfill_start_date, models_to_remove: snowplow_web_custom_incremental_model}'` command, with your model name and a specific start date.
2. The log should contain `Snowplow: New Snowplow incremental model. Backfilling` which identifies the model has been reset.
3. Complete as many runs selecting just your model or the tag as needed to fully backfill the custom model.

Can you let me know if this solves your problem, if not can you share the output of your dbt run command when you run with the `models_to_remove` variable please so we can help identify the issue.

**Comment by rlh1994** [comment]
Due to no response we will be closing this issue, if you are still seeing this issue please let us know as we can re-open.
