### ISSUE TITLE
Custom `..._this_run` tables need to be tagged

### ISSUE THREAD

**Issue by awoehrl** [snowplow/dbt-snowplow-web#199]
## Describe the bug
It seems like custom tables building on top of `snowplow_web_base_events_this_run` need to be tagged with `snowplow_web_incremental`  in order for them to work.
If I'm not tagging them, I'm getting the following error:

`Snowplow Warning: Untagged models referencing 'snowplow_web_base_events_this_run'. Please refer to the Snowplow docs on tagging. Models: custom_model_this_run`

## Steps to reproduce
Create a custom model in a dbt folder that has no tags associated
The example below just used one of the models in custom_example and replaced `snowplow_web_page_views_this_run` with `snowplow_web_base_events_this_run` to replicate the problem:

```
-- `this_run` table so calc in drop and recompute fashion. This will be joined into the `snowplow_web_sessions_custom` incremental table 
{{ 
  config(
    materialized='table',
    sort='domain_sessionid',
    dist='domain_sessionid',
    sql_header=snowplow_utils.set_query_tag(var('snowplow__query_tag', 'snowplow_dbt')),
  ) 
}}

select 
  domain_sessionid,
  cast(sum(case when page_urlpath like 'https://www.mysite.com/products%' then 1 else 0 end) as boolean) as is_session_w_intent,
  cast(sum(case when page_urlpath like 'https://www.mysite.com/order_complete%' then 1 else 0 end) as boolean) as is_session_w_conversion

from {{ ref('snowplow_web_base_events_this_run') }} pv
group by 1
```

## Expected results
The model should work without tagging according to the docs here: https://docs.snowplow.io/docs/modeling-your-data/modeling-your-data-with-dbt/dbt-custom-models/#this-run-models

## Actual results
```
Snowplow Warning: Untagged models referencing 'snowplow_web_base_events_this_run'. Please refer to the Snowplow docs on tagging. Models: custom_model_this_run
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] databricks
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
Core:
  - installed: 1.4.5
  - latest:    1.5.1 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - bigquery: 1.4.3 - Update available!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation
```

**Version of dbt-snowplow-web**
0.14.0

**Comment by rlh1994** [comment]
@awoehrl Thanks for flagging this, it looks like our docs are incorrect and even `..._this_run` tables need to be tagged to ensure they are parsed correctly. I've got a PR raised into the docs and expect this to be merged later today, so I'll close this issue now.
