### ISSUE TITLE
Is there any method or feature available in the pakage for set a custom eastern timestamp

### ISSUE THREAD

**Issue by Naveenzerobugz** [snowplow/dbt-snowplow-web#221]
### Discussed in https://github.com/snowplow/dbt-snowplow-web/discussions/220

<div type='discussions-op-text'>

<sup>Originally posted by **Naveenzerobugz** August  4, 2023</sup>
To display the dashboard in Eastern Time instead of UTC, I need to adjust the timezone setting to switch it to Estern Time Zone.
can you help me setup a custom timestamp? this package 
like this 'snowplow:timezone': 'America/New_York'</div>

**Comment by miike** [comment]
Hi Naveen - as @rlh1994 has mentioned we aim to keep all models in UTC and leave it up to the user to convert to the appropriate timezone in their own data models or at presentation time.
