### ISSUE TITLE
persist_docs fails with missing event_counts on snowplow_web_sessions_this_run on Databricks

### ISSUE THREAD

**Issue by dkbrkjni** [snowplow/dbt-snowplow-web#234]
## Steps to reproduce
In dbt_project.yml
Add:
```
models:
  +persist_docs:
    relation: true
    columns: true
```
Remove `snowplow__list_event_counts` variable, if set.

run `dbt run`

## Expected results
Descriptions persisted to database

## Actual results
Error: missing event_counts on snowplow_web_sessions_this_run

## Screenshots and log output
![image](https://github.com/snowplow/dbt-snowplow-web/assets/14215821/8b1cc153-c0f0-476d-be5e-be529a5fb35b)

## System information
**The contents of your `packages.yml` file:**
```yml
# contents goes here
```

**Which database are you using dbt with?**
- [ ] postgres
- [x] redshift
- [ ] bigquery
- [ ] snowflake
- [x] databricks
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
1.6.9

**The operating system you're using:**

**The output of `python --version`:**

**Comment by rlh1994** [comment]
Hi @dkbrkjni , I'm able to replicate this on databricks (although oddly, not on all other warehouse, I'm still testing a few of them).

We're planning a few small updates to the web package soon, so we will in this as a fix in part of it. I may also raise this as a bug with dbt-databricks as it seems odd that the other warehouses support defining a column that may not exist (so long as a contract is not enforced).

**Comment by rlh1994** [comment]
@dkbrkjni I've raised the issue linked above directly with the dbt-databricks maintainers, they were actually already looking at the `persist docs` behaviour so it was perfectly timed! They have a fix in an upcoming version (due out maybe this week) that will validate the columns in the warehouse against the yaml and only comment those columns that exist. This is how other connectors manage it, and means we don't need to remove the docs from the package.

I'll keep this issue open until that version is released, but I believe that should resolve the problem!

**Comment by dkbrkjni** [comment]
> @dkbrkjni can you confirm if you still see this issue if you upgrade to 1.7.2 of the databricks connector pleaase? https://github.com/databricks/dbt-databricks/releases/tag/v1.7.2

Sorry we have been busy, but I hope to tests this within this week.
