### ISSUE TITLE
BQ Only: Cluster by in users_lasts is incorrectly configured

### ISSUE THREAD

**Issue by emielver** [snowplow/dbt-snowplow-web#59]
### Describe the bug
The following line references the `domain_sessionid` to cluster by when running the model in BigQuery:
https://github.com/snowplow/dbt-snowplow-web/blob/b12e45d4cd298f330a4df399813a5645a9c95303/models/users/scratch/snowplow_web_users_lasts.sql#L3

The `domain_sessionid` is not a column that exists in the table generated, and therefore BQ throws an error when dbt tries to cluster by `domain_sessionid`. It is currently not a problem because we materialise this data as a view and therefore `cluster_by` does not do anything. However if we were to materialise this data as a table, BQ would throw an error and the model would not work. 
### Steps to reproduce
Add a line in the config saying `materialize='table',`
https://github.com/snowplow/dbt-snowplow-web/blob/b12e45d4cd298f330a4df399813a5645a9c95303/models/users/scratch/snowplow_web_users_lasts.sql#L2

### Expected results
No errors

### Actual results
```
Completed with 1 error and 0 warnings:

Database Error in model snowplow_web_users_lasts (models/users/scratch/snowplow_web_users_lasts.sql)
Unrecognized name: domain_sessionid at [6:14]
compiled SQL at target/run/snowplow_web/models/users/scratch/snowplow_web_users_lasts.sql
```

### System information
**The contents of your `packages.yml` file:**
```
packages:
  - package: snowplow/snowplow_utils
    version: [">=0.6.0", "<0.7.0"]
```
**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 1.0.0
   latest version: 1.0.0

Up to date!

Plugins:
  - bigquery: 1.0.0
  - snowflake: 0.21.1
  - redshift: 0.21.1
  - postgres: 0.21.1
```

**The operating system you're using:**
Mac OS Monterrey 12.1
**The output of `python --version`:**
Python 3.9.9

**Comment by bill-warner** [comment]
Good spot!
