### ISSUE TITLE
The package seems to break the dbt docs lineage graph view

### ISSUE THREAD

**Issue by LuisCebrian** [snowplow/dbt-snowplow-web#73]
### Describe the bug
Hi there,

After installing and running the snowplow package, the lineage graph view of the dbt docs website is broken. When I open the view from the button at the bottom right corner of the screen (Picure 1) the view opens with a green dot in the screen instead of the whole project graph (Picture 2). Moreover, I can only see some nodes if I indicate something in the `--select` filter. The other filters such as resources, packages and tags do not work at all.

Thank you in advance and sorry if this has been asked before, I have not found anything about this issue.

### Steps to reproduce
- Install the snowplow package
- Generate the dbt website with `dbt docs generate` and `dbt docs serve`
- Go to the website in your browser
- Open the lineage graph view from the button at the bottom right corner of the screen.

### Expected results
I should be able to see the whole graph if I open the lineage graph without any filters and I should be able to filter the nodes in the lineage graph with the different UI filters.

### Actual results
I cannot see the lineage graph, and the UI filters do not do anything.

### Screenshots and log output
[Picture 1]
![image](https://user-images.githubusercontent.com/4885095/163203570-739ee93e-0e9f-47a2-b51c-19f8850ff754.png)

[Picture 2]
![image](https://user-images.githubusercontent.com/4885095/163203479-78b43e37-23f5-4492-9d5e-239c70879600.png)

### System information
packages.yml
```
packages:
  - package: dbt-labs/dbt_utils
    version: 0.8.0
  - package: snowplow/snowplow_web
    version: 0.6.0
```

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [x] bigquery
- [ ] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 1.0.0
   latest version: 1.0.0

Up to date!

Plugins:
  - bigquery: 1.0.0
```

**The operating system you're using:**
Ubuntu 20.04

**The output of `python --version`:**
`Python 3.8.10`

### Additional context
From the logs on the browser it seems there is something wrong with `operation.snowplow_web.snowplow_web-on-run-end-0` and `operation.snowplow_web.snowplow_web-on-run-start-0`
![image](https://user-images.githubusercontent.com/4885095/163204586-4b434c5e-49f0-4aea-aa5c-10f67897fd5f.png)

**Comment by LuisCebrian** [comment]
This was a dbt-docs issue that was addressed [here](https://github.com/dbt-labs/dbt-docs/issues/229). Upgrading to v.1.0.5 solved the issue.

**Comment by paulboocock** [comment]
Thanks for letting us know this is fixed @LuisCebrian 👍
