### ISSUE TITLE
absolute_time_in_s skewed by late page_ping

### ISSUE THREAD

**Issue by hubertpb** [snowplow/dbt-snowplow-web#96]
### Describe the bug

I noticed very long (multiple days) average session durations in the derived `snowplow_web_sessions`. The average session duration is based on the field `absolute_time_in_s` which comes from the package. this field is the time difference between `start_tstamp` and `end_tstamp` I then had a look at a few sessions affected and queried the atomic events table to see all the events of these sessions.

I have identified the issue as coming from "page_pings" events (heartbeats) happening multiple days after the visit: the `domain_sessionid` will be different, but the `page_view_id` is the same.

absolute_time_in_s is calculated in the model [`snowplow_web_page_views_this_run`](https://github.com/snowplow/dbt-snowplow-web/blob/b41150684b6a3d63789178b4299a7a5c3a37cd43/models/page_views/scratch/snowflake/snowplow_web_page_views_this_run.sql#L219):
`timediff(second, p.derived_tstamp, coalesce(t.end_tstamp, p.derived_tstamp))  as absolute_time_in_s`

`t.end_tstamp` comes from the model [`snowplow_web_pv_engaged_time`](https://github.com/snowplow/dbt-snowplow-web/blob/main/models/page_views/scratch/snowplow_web_pv_engaged_time.sql) which calculates the timestamp grouping by the `page_view_id` field. A same page_view_id can happen across multiple sessions which causes the `end_tstamp` to be erronous and therefore the `absolute_time_in_s` field too.

Could the `snowplow_web_pv_engaged_time` be calculated based on the `domain_sessionid` and the `page_view_id`?

### System information
**The contents of your `packages.yml` file:**
packages:
  - package: dbt-labs/dbt_utils
    version: 0.8.4
  - package: tnightengale/dbt_meta_testing
    version: 0.3.5
  - package: snowplow/snowplow_web
    version: 0.6.0
  - package: Montreal-Analytics/snowflake_utils
    version: 0.3.0

**Which database are you using dbt with?**
- [ ] postgres
- [ ] redshift
- [ ] bigquery
- [X] snowflake
- [ ] other (specify: ____________)

**The output of `dbt --version`:**
```
installed version: 1.0.4
   latest version: 1.1.1

Your version of dbt is out of date! You can find instructions for upgrading here:
https://docs.getdbt.com/docs/installation

Plugins:
  - postgres: 0.21.0 - Out of date!
  Your version of dbt-postgres is out of date! You can find instructions for upgrading here:
  https://docs.getdbt.com/dbt-cli/install/overview

  - redshift: 0.21.0 - Out of date!
  Your version of dbt-redshift is out of date! You can find instructions for upgrading here:
  https://docs.getdbt.com/dbt-cli/install/overview

  - snowflake: 1.0.0 - Update available!
  Your version of dbt-snowflake is out of date! You can find instructions for upgrading here:
  https://docs.getdbt.com/dbt-cli/install/overview
```

**The operating system you're using:**
Windows for local development. Linux for prod on an EC2
**The output of `python --version`:**
Python 3.9.7
### Are you interested in contributing the fix?

I'll let you fix it, the package is complex!

**Comment by hubertpb** [comment]
Is this something I should flag in the discourse channel?

**Comment by paulboocock** [comment]
Hey @hubertpb 
You're fine to raise this here. We monitor both places, Discourse is usually better for conversations or help, but this does feel like a bug - I'll raise it with the team, I certainly have some recollection of us discussing this previously. We've been at our annual company retreat recently, which is why we haven't been as active, apologies!

**Comment by rlh1994** [comment]
@hubertpb Sorry for the delay in this, we spent quite a bit of time trying to find the best way to address this between tracking and modelling, but version 0.12.1 now has (by default) the time being calculated and joined by page view id AND session id, hopefully this works for you, if not please let us know!
